weekend_blog_lab-1-master/config/routes.rb
Rails.application.routes.draw do
  root 'authors#index'
  resources :authors do
    resources :posts, shallow:true 
  end

end

weekend_blog_lab-1-master/app/models/author.rb
class Author < ActiveRecord::Base
  validates :first_name, :last_name, presence: true, length: {in: 4...20}
  validates :age, numericality: true 
  has_many :posts, dependent: :destroy
end

weekend_blog_lab-1-master/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :body, :category, presence:true 
  validates :title, length: {minimum:3}
  belongs_to :author
end

weekend_blog_lab-1-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

weekend_blog_lab-1-master/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def edit
    @author = Author.find(params[:id])
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params
    if @author.save
      redirect_to authors_path
    else
      render :new
    end
  end

  def update
    @author = Author.find(params[:id])
    @author.update_attributes author_params
    if @author.save
      redirect_to author_path(@author)
    else 
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name, :age)
  end  
end

weekend_blog_lab-1-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @author = Author.find(params[:author_id]) 
    @posts = @author.posts
  end

  def edit
    @post = Post.find(params[:id])
    @author = @post.author
  end

  def show
    @post = Post.find(params[:id])
    @author = @post.author
  end

  def new
    @author = Author.find(params[:author_id])
    @post = Post.new 
  end

  def create
    @author = Author.find(params[:author_id])
    @post = Post.new post_params
    @post.author = @author 
    @author.posts << @post 
    if @post.save
      redirect_to author_posts_path(@author)
    else
      render :new 
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes post_params
    @author = @post.author
      if @post.save 
        redirect_to post_path(@post)
      else
      render :edit 
      end 
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to author_posts_path(post.author)
  end

  private 
  def post_params
    params.require(:post).permit(:title, :body, :category, :author_id)
  end
end

weekend_blog_lab-1-master/app/helpers/application_helper.rb
module ApplicationHelper
end

weekend_blog_lab-1-master/app/helpers/authors_helper.rb
module AuthorsHelper
end

weekend_blog_lab-1-master/app/helpers/posts_helper.rb
module PostsHelper
end

weekend_blog_lab-1-master/app/views/authors/edit.html.erb
<div class="container-fluid">

  <% if @author.errors.any?%>
  <% @author.errors.full_messages.each do |error|%>
  <p class = "text-danger">
    <%= error %>
  </p>
  <% end %>
  <% end %>

  <h2>Add Author Here:</h2>

  <%= form_for(@author, :html => { :class => "form-horizontal" }) do |f|%>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br />
  
  <%= f.label :last_name %>

  <%= f.text_field :last_name %><br />

  <%= f.label :age %>
  <%= f.text_field :age%><br />

  <br>
  <%= f.submit "Edit Author", class: 'btn btn-success' %>
  <br><br>
  <%=  link_to('Back to Authors', root_path, {class: "btn btn-success"}) %>
  <% end %>
</div>

weekend_blog_lab-1-master/app/views/authors/index.html.erb
<div class="container-fluid">

<h2 class = "text-center">Authors:</h2>
<br>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
<div class="row">
<div class ="col-md-10 col-md-offset-1">
<table class ="table table-striped">
<tr>
<th>First Name</th>
<th>Last Name</th>
<th>Age</th>
<th>Info</th>
<th>Edit</th>
<th>Delete</th>
</tr>
<% @authors.each do |author| %>
  <tr >
    <td ><%=author.first_name  %></td>
    <td ><%= author.last_name %></td>
    <td><%= author.age %></td>
    <td><%= link_to('Info', author_path(author), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Edit', edit_author_path(author), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Delete',author_path(author), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
  </tr>
  <%end %>
</table>
</div>
</div>

<div class="row">
<div class ="col-md-2 col-md-offset-1">
<%=  link_to('Add new author', new_author_path, {class: "btn btn-success"}) %>
</div>
</div>
</div>

weekend_blog_lab-1-master/app/views/authors/new.html.erb
<div class="container-fluid">

  <% if @author.errors.any?%>
  <% @author.errors.full_messages.each do |error|%>
  <p class = "text-danger">
    <%= error %>
  </p>
  <% end %>
  <% end %>
  <br>
  <h2 class ="text-center">Add Author Here:</h2>
  <br>

<%= form_for(@author, :html => { :class => "form-horizontal" }) do |f|%>
<div class = row>
<div class="col-md-3 col-md-offset-2">
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br />
</div>
  <div class="col-md-3">
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br />
  </div>
 <div class="col-md-3">
  <%= f.label :age %>
  <%= f.text_field :age%><br />
  </div>
  </div>
  <br>
  <div class ="row">
  <div class = "col-md-3 col-md-offset-2">
  <%=  link_to('Back to Authors', root_path, {class: "btn btn-success"}) %>
  </div>
  <div class ="col-md-3">
  <%= f.submit "Add Author", class: 'btn btn-success' %>
  </div>
  </div>
  <% end %>
</div>

weekend_blog_lab-1-master/app/views/authors/show.html.erb
<div class="container-fluid">

<h2 class = "text-center">Authors:</h2>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->

<table class ="table table-striped">
<tr>
<th>First Name</th>
<th>Last Name</th>
<th>Age</th>
</tr>
  <tr >
    <td ><%=@author.first_name  %></td>
    <td ><%= @author.last_name %></td>
    <td><%= @author.age %></td>
  </tr>
</table>

<%=  link_to('See Blog Posts', author_posts_path(@author), {class: "btn btn-success"}) %>
<br><br>
<%=  link_to('Back to Authors', root_path, {class: "btn btn-success"}) %>

</div>

weekend_blog_lab-1-master/app/views/posts/edit.html.erb
<div class="container-fluid">

  <% if @post.errors.any?%>
  <% @post.errors.full_messages.each do |post|%>
  <p class = "text-danger">
    <%= error %>
  </p>
  <% end %>
  <% end %>

  <h2>Edit Post Here:</h2>

  <%= form_for(@post, :html => { :class => "form-horizontal" }) do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %><br />
  
  <%= f.label :category %>
  <%= f.text_field :category %><br />

  <%= f.label :body %>
  <%= f.text_field :body%><br />

  <br>
  <%= f.submit "Edit Post", class: 'btn btn-success' %>
  <br><br>
  <%=  link_to('Back to Posts',author_posts_path(@author) , {class: "btn btn-success"}) %>
  <% end %>
</div>

weekend_blog_lab-1-master/app/views/posts/index.html.erb
<div class="container-fluid">

<h2 class = "text-center"><%= @author.first_name%> <%= @author.last_name %> Posts</h2>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->

<table class ="table table-striped">
<tr>
<th>Title</th>
<th>Category</th>
<th>Info</th>
<th>Edit</th>
<th>Delete<th>
</tr>
<% @posts.each do |post| %>
  <tr >
    <td ><%=post.title  %></td>
    <td><%= post.category %></td>
    <td><%= link_to('Info', post_path(post), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Edit', edit_post_path(post), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Delete',post_path(post), method: :delete, data: { confirm: "Are you sure?" },class: "btn-xs btn-danger")%></td>
  </tr>
  <%end %>
</table>

<%=  link_to('Add new Post', new_author_post_path, {class: "btn btn-success"}) %>
<br><br>
<%=  link_to('Back to All Authors', root_path, {class: "btn btn-success"}) %>

</div>

weekend_blog_lab-1-master/app/views/posts/new.html.erb
<div class="container-fluid">

  <% if @post.errors.any?%>
  <% @post.errors.full_messages.each do |error|%>
  <p class = "text-danger">
    <%= error %>
  </p>
  <% end %>
  <% end %>
  <br>
  <h2 class ="text-center">Add Blog Post Here:</h2>
  <br>

<%= form_for([@author,@post], :html => { :class => "form-horizontal" }) do |f|%>
<div class = row>
<div class="col-md-3 col-md-offset-2">
  <%= f.label :title %>
  <%= f.text_field :title %><br />
</div>
  <div class="col-md-3">
  <%= f.label :category %>
  <%= f.text_field :category %><br />
  </div>
 <div class="col-md-3">
  <%= f.label :body %>
  <%= f.text_field :body%><br />
  </div>
  </div>
  <br>
  <div class ="row">
  <div class = "col-md-3 col-md-offset-2">
  <%=  link_to('Back to Author', root_path, {class: "btn btn-success"}) %>
  </div>
  <div class ="col-md-3">
  <%= f.submit "Add Post", class: 'btn btn-success' %>
  </div>
  </div>
  <% end %>
</div>

weekend_blog_lab-1-master/app/views/posts/show.html.erb
<div class="container-fluid">

<h2 class = "text-center"><%= @post.title%></h2>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->

<table class ="table table-striped">
<tr>
<th>Title</th>
<th>Category</th>
<th>Edit</th>
<th>Delete</th>
</tr>
  <tr >
    <td ><%=@post.title %></td>
    <td><%= @post.category %></td>
    <td><%= link_to('Edit', edit_post_path(@post), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Delete',post_path(@post), method: :delete, data: { confirm: "Are you sure?" },class: "btn-xs btn-danger")%></td>
  </tr>
</table>
<p class = "text-center"><%=@post.body%></p>
<br>
<%=  link_to('Back to Author', author_posts_path(@author), {class: "btn btn-success"}) %>
</div>