actors_and_movies_lab-master/config/routes.rb
Rails.application.routes.draw do
  root 'landingpage#index'
  resources :movies, :actors, :landingpage

<<<<<<< HEAD
=======
  resources :movies
  resources :actors

  post 'movies/:movie_id/comments' => 'comments#create', as: 'movie_comments'
  delete 'movies/:movie_id/comments' => 'comments#remove_movie_comment', as: :remove_movie_comment
  
  post 'actors/:actor_id/comments' => 'comments#create', as: 'actor_comments'  
  delete 'actors/:actor_id/comments' => 'comments#remove_actor_comment', as: :remove_actor_comment


  post '/movies/:id/actors/new' => 'movies#add_actor', as: :add_actor
  delete 'movies/:id/actors/:actor_id' => 'movies#remove_actor', as: :remove_actor

  post '/actors/:id/movies/new' => 'actors#add_movie', as: :add_movie
  delete '/actors/:id/movies/:movie_id' => 'actors#remove_movie', as: :remove_movie

  root 'site#index'
>>>>>>> b6f563e4e6ddbbc2addd3b2b5d4ed2beb35a8b05

end

actors_and_movies_lab-master/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:edit, :show, :destroy, :add_actor, :remove_actor]
  
  def index
    @movies = Movie.all
  end

  def create
    Movie.create movie_params 
    redirect_to movies_path
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def show
    @actors = Actor.all - @movie.actors
    @commentable = @movie
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def update
    @movie.update_attributes movie_params
    redirect_to @movie
  end
  
  def add_actor
    movie = Movie.find(params[:id])
    actor = Actor.find(params[:actor_id])
    movie.actors << actor
    redirect_to movie_path(movie)
  end

  def remove_actor
    movie = Movie.find(params[:id])
    actor = Actor.find(params[:actor_id])
    movie.actors.delete(actor)
    redirect_to movie_path(movie)
  end
  
  def destroy
    @movie.destroy
    redirect_to movies_path
  end

<<<<<<< HEAD
  private 
    def movie_params
      params.require(:movie).permit(:title, :year)
    end
=======
  def add_actor
    actor = Actor.find(actor_params[:id])
    unless @movie.actors.include? actor
      @movie.actors << actor
    end
    redirect_to @movie
  end

  def remove_actor
    @movie.actors.delete(Actor.find(params[:actor_id]))
    redirect_to @movie 
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :year)
  end

  def actor_params
    params.require(:actor).permit(:id, :name)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
>>>>>>> b6f563e4e6ddbbc2addd3b2b5d4ed2beb35a8b05
end

actors_and_movies_lab-master/app/helpers/movies_helper.rb
module MoviesHelper
end

actors_and_movies_lab-master/app/views/movies/edit.html.erb
<h1>Edit Movie Info</h1>

<%= form_for @movie do |f| %>
  <h4>Movie Title
  <%= f.text_field :title %></h4>
  <h4>Year Released
  <%= f.text_field :year %></h4>
  <%= f.submit "Update" %>
<% end %>

actors_and_movies_lab-master/app/views/movies/index.html.erb
<h1>Movies</h1>

<ul>
  <% @movies.each do |film| %>
  <li><%= link_to "#{film.title} (#{film.year})", film %></li>
  <% end %>
</ul>

<%= link_to "Add movie", new_movie_path %>
<<<<<<< HEAD
<%= link_to "Back", :root %>
=======
<br><br>
<%= link_to "Back to home", root_path %>
>>>>>>> b6f563e4e6ddbbc2addd3b2b5d4ed2beb35a8b05

actors_and_movies_lab-master/app/views/movies/new.html.erb
<h1>Add a new movie</h1>

<%= form_for @movie do |f| %>
  <%= f.text_field :title, :placeholder => "Title" %>
  <%= f.text_field :year, :placeholder => "Year" %>
  <%= f.submit "Add" %>
<% end %>

actors_and_movies_lab-master/app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<p><%= @movie.year %></p>

<div class="black-box">
  <h2>Actors</h2>
  <ul>
    <% @movie.actors.each do |actor| %>
    <li>
      <%= link_to actor.name, actor %>
      <%= button_to "X", remove_actor_path(@movie, actor), :method => :delete %>
    </li>
    <% end %>
  </ul>
  <% unless @actors.empty? %>
  <%= form_tag add_actor_path(@movie) do %>
  <%= collection_select :actor, :id, @actors, :id, :name %>
  <%= submit_tag "Add" %>
  <% end %>
  <% end %>
</div>

<%= link_to "Edit", edit_movie_path(@movie) %>
<%= button_to "Delete", movie_path(@movie), :method => :delete %>
<br><br>

<div class="commentBox">
  <h1>Comments</h1>

  <% @comments.each do |comment| %>
  <div class="comment">
    <h4><%= simple_format comment.content %></h4> 
    <p><%= time_ago_in_words comment.created_at %>
    <%= button_to "X", remove_movie_comment_path(@comments, comment), :method => :delete %></p>
  </div>
  <% end %>
</div>

<i><h4>Post a New Comment!</h4></i>
  <%= form_for [@commentable, @comment] do |f| %>
    <% if @comment.errors.any? %>
      <div class="error">
          <h2>Please correct the following errors</h2>
      <ul>
          <% @comment.errors.full_message.each do |msg| %>
              <li> <%= msg %> </li>
          <% end %>
      </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.text_area :content, rows: 8 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<br><br>
<%= link_to "Back to movies", movies_path %>